language: python
python:
    - "2.7"
# command to install dependencies
install: "python setup.py develop"
# command to run tests
script: "sudo sh -c \". $VIRTUAL_ENV/bin/activate; python setup.py test\""
