.. Global includes, substitutions, and common links.

.. _website: https://bastio.com
.. _code repository: http://github.com/Databracket/bastio-agent
.. _issue tracker: http://github.com/Databracket/bastio-agent/issues
.. _PPA repository: https://launchpad.net/bastio-agent
.. _PyPI repository: https://pypi.python.org/pypi/Bastio-Agent
.. _support email: support@bastio.com

.. _PyPI: https://pypi.python.org/pypi
.. _pip: https://pypi.python.org/pypi/pip
.. _virtualenv: http://www.virtualenv.org/
.. _github: http://github.com/
.. _git: http://git-scm.org/
.. _ssh: http://www.openssh.org/
.. _Python: http://python.org/
.. _Paramiko: https://pypi.python.org/pypi/paramiko
.. _Requests: http://python-requests.org/
.. _LSB: http://refspecs.linuxfoundation.org/LSB_3.1.0/LSB-Core-generic/LSB-Core-generic/tocsysinit.html
.. _Ubuntu Synchronizing Key Server: http://keyserver.ubuntu.com/
